### ISSUE TITLE
Color is not applied in chat

### ISSUE THREAD

**Issue by gegtor** [DiFFoZ/PermissionExtensions#3]
Both hex color and word color are used in config but it's not applied in chat

```
roles:
- id: default
  priority: 0
  parents: []
  permissions:
  - Rocket.PermissionLink:vault
  - Rocket.PermissionLink:vaults
  - Rocket.PermissionLink:trash
  - Rocket.PermissionLink:tpa
  - Rocket.PermissionLink:tpa.send
  - Rocket.PermissionLink:tpa.accept
  - Rocket.PermissionLink:tpa.cancel
  - Rocket.PermissionLink:tpa.deny
  - Rocket.PermissionLink:essentials.command.home
  - Rocket.PermissionLink:essentials.command.kit
  - Rocket.PermissionLink:essentials.command.kits
  - Rocket.PermissionLink:essentials.textcommand.shop
  - Rocket.PermissionLink:report
  - Rocket.PermissionLink:discord
  - Rocket.PermissionLink:link
  - Rocket.PermissionLink:voterewards.vote
  - Rocket.PermissionLink:voterewards.reward
  - Rocket.PermissionLink:voterewards.givereward
  displayName: Default
  data:
    color: Green
    prefix: '[Member] '
    suffix: ''
  isAutoAssigned: true
- id: vip-1
  priority: 1
  parents:
  - default
  permissions:
  - Rocket.PermissionLink:vault
  - Rocket.PermissionLink:vaultplugin.vip1
  - Rocket.PermissionLink:essentials.kit.scrap-1
  - Rocket.PermissionLink:essentials.kit.military-russia-1
  - Rocket.PermissionLink:essentials.kit.specops-1
  - Rocket.PermissionLink:essentials.kit.military-washington-1
  - Rocket.PermissionLink:heal
  - Rocket.PermissionLink:essentials.command.maxskills
  - Rocket.PermissionLink:essentials.command.repairvehicle
  - Rocket.PermissionLink:essentials.command.refuelvehicle
  - Rocket.PermissionLink:essentials.command.refuelgenerator
  - Rocket.PermissionLink:essentials.command.repair
  displayName: vip-1
  data:
    color: '#f5af47'
    prefix: '[VIP-1] '
    suffix: ''
    cooldowns:
    - command: Rocket.PermissionLink:heal
      cooldown: 5 hours
    - command: Rocket.PermissionLink:essentials.command.maxskills
      cooldown: 5 hours
    - command: Rocket.PermissionLink:essentials.command.repairvehicle
      cooldown: 5 hours
    - command: Rocket.PermissionLink:essentials.command.refuelvehicle
      cooldown: 5 hours
    - command: Rocket.PermissionLink:essentials.command.refuelgenerator
      cooldown: 5 hours
    - command: Rocket.PermissionLink:essentials.command.repair
      cooldown: 5 hours
  isAutoAssigned: false
- id: vip-2
  priority: 2
  parents:
  - default
  permissions:
  - Rocket.PermissionLink:vault
  - Rocket.PermissionLink:vaultplugin.vip2
  - Rocket.PermissionLink:essentials.kit.scrap-2
  - Rocket.PermissionLink:essentials.kit.military-russia-2
  - Rocket.PermissionLink:essentials.kit.specops-2
  - Rocket.PermissionLink:essentials.kit.military-washington-2
  - Rocket.PermissionLink:heal
  - Rocket.PermissionLink:essentials.command.maxskills
  - Rocket.PermissionLink:essentials.command.repairvehicle
  - Rocket.PermissionLink:essentials.command.refuelvehicle
  - Rocket.PermissionLink:essentials.command.refuelgenerator
  - Rocket.PermissionLink:essentials.command.repair
  displayName: vip-2
  data:
    color: '#4aff68'
    prefix: '[VIP-2] '
    suffix: ''
    cooldowns:
    - command: Rocket.PermissionLink:heal
      cooldown: 3 hours
    - command: Rocket.PermissionLink:essentials.command.maxskills
      cooldown: 3 hours
    - command: Rocket.PermissionLink:essentials.command.repairvehicle
      cooldown: 3 hours
    - command: Rocket.PermissionLink:essentials.command.refuelvehicle
      cooldown: 3 hours
    - command: Rocket.PermissionLink:essentials.command.refuelgenerator
      cooldown: 3 hours
    - command: Rocket.PermissionLink:essentials.command.repair
      cooldown: 3 hours
  isAutoAssigned: false
- id: vip-3
  priority: 3
  parents:
  - default
  permissions:
  - Rocket.PermissionLink:vault
  - Rocket.PermissionLink:vaultplugin.vip3
  - Rocket.PermissionLink:essentials.kit.scrap-3
  - Rocket.PermissionLink:essentials.kit.military-russia-3
  - Rocket.PermissionLink:essentials.kit.specops-3
  - Rocket.PermissionLink:essentials.kit.military-washington-3
  - Rocket.PermissionLink:heal
  - Rocket.PermissionLink:essentials.command.maxskills
  - Rocket.PermissionLink:essentials.command.repairvehicle
  - Rocket.PermissionLink:essentials.command.refuelvehicle
  - Rocket.PermissionLink:essentials.command.refuelgenerator
  - Rocket.PermissionLink:essentials.command.repair
  displayName: vip-3
  data:
    color: '#9066de'
    prefix: '[VIP-3] '
    suffix: ''
    cooldowns:
    - command: Rocket.PermissionLink:heal
      cooldown: 1 hour
    - command: Rocket.PermissionLink:essentials.command.maxskills
      cooldown: 1 hour
    - command: Rocket.PermissionLink:essentials.command.repairvehicle
      cooldown: 1 hour
    - command: Rocket.PermissionLink:essentials.command.refuelvehicle
      cooldown: 1 hour
    - command: Rocket.PermissionLink:essentials.command.refuelgenerator
      cooldown: 1 hour
    - command: Rocket.PermissionLink:essentials.command.repair
      cooldown: 1 hour
  isAutoAssigned: false
- id: veteran
  priority: 4
  parents:
  - vip-3
  permissions:
  - Rocket.PermissionLink:vault
  displayName: veteran
  data:
    color: '#65e6c1'
    prefix: '[Veteran] '
    suffix: ''
  isAutoAssigned: false
- id: helper
  priority: 5
  parents:
  - vip-3
  permissions:
  - Rocket.PermissionLink:vault
  displayName: helper
  data:
    color: '#3d94ff'
    prefix: '[Helper] '
    suffix: ''
  isAutoAssigned: false
- id: admin
  priority: 6
  parents:
  - vip-3
  permissions:
  - Rocket.PermissionLink:vault
  displayName: admin
  data:
    color: '#fc38cf'
    prefix: '[Admin] '
    suffix: ''
  isAutoAssigned: false
```
